name: Release new version

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get version from init file
        id: get_version
        run: |
          echo "VERSION=${{ github.event.repository.name }}-v$(grep -o -E '"version":\s*\(\d+,\s*\d+,\s*\d+' addons/${{ github.event.repository.name }}/__init__.py \
          | sed -E 's/"version": *\(//; s/, */./g')" >> $GITHUB_ENV

      - name: Create archive
        run: zip -r ${{ env.VERSION }}.zip addons/${{ github.event.repository.name }}
        working-directory: ${{ github.workspace }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.VERSION }}.zip
          asset_name: ${{ env.VERSION }}.zip
          asset_content_type: application/zip
